//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kranon.webApp_LibreriaKranon.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LKEntities : DbContext
    {
        public LKEntities()
            : base("name=LKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libros> Libros { get; set; }
    
        public virtual ObjectResult<SP_AllR_Result> SP_AllR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AllR_Result>("SP_AllR");
        }
    
        public virtual int SP_Autor_Eliminar(string autor)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Autor_Eliminar", autorParameter);
        }
    
        public virtual int SP_Editorial_Eliminar(string editorial)
        {
            var editorialParameter = editorial != null ?
                new ObjectParameter("Editorial", editorial) :
                new ObjectParameter("Editorial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Editorial_Eliminar", editorialParameter);
        }
    
        public virtual ObjectResult<SP_Gby_Anio_Result> SP_Gby_Anio(Nullable<int> anio_publicacion)
        {
            var anio_publicacionParameter = anio_publicacion.HasValue ?
                new ObjectParameter("anio_publicacion", anio_publicacion) :
                new ObjectParameter("anio_publicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gby_Anio_Result>("SP_Gby_Anio", anio_publicacionParameter);
        }
    
        public virtual ObjectResult<SP_Gby_Autor_Result> SP_Gby_Autor(string autor)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gby_Autor_Result>("SP_Gby_Autor", autorParameter);
        }
    
        public virtual ObjectResult<SP_Gby_AutoryAnio_Result> SP_Gby_AutoryAnio(string autor, Nullable<int> anio_publicacion)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));
    
            var anio_publicacionParameter = anio_publicacion.HasValue ?
                new ObjectParameter("anio_publicacion", anio_publicacion) :
                new ObjectParameter("anio_publicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gby_AutoryAnio_Result>("SP_Gby_AutoryAnio", autorParameter, anio_publicacionParameter);
        }
    
        public virtual ObjectResult<SP_Gby_Editorial_Result> SP_Gby_Editorial(string editorial)
        {
            var editorialParameter = editorial != null ?
                new ObjectParameter("Editorial", editorial) :
                new ObjectParameter("Editorial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gby_Editorial_Result>("SP_Gby_Editorial", editorialParameter);
        }
    
        public virtual ObjectResult<SP_Gby_Titulo_Result> SP_Gby_Titulo(string titulo)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Gby_Titulo_Result>("SP_Gby_Titulo", tituloParameter);
        }
    
        public virtual int SP_Libro_Ins(string autor, string titulo, Nullable<int> anio_publicacion, string editorial)
        {
            var autorParameter = autor != null ?
                new ObjectParameter("Autor", autor) :
                new ObjectParameter("Autor", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var anio_publicacionParameter = anio_publicacion.HasValue ?
                new ObjectParameter("anio_publicacion", anio_publicacion) :
                new ObjectParameter("anio_publicacion", typeof(int));
    
            var editorialParameter = editorial != null ?
                new ObjectParameter("Editorial", editorial) :
                new ObjectParameter("Editorial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Libro_Ins", autorParameter, tituloParameter, anio_publicacionParameter, editorialParameter);
        }
    }
}
